from datetime import datetime
from elasticsearch import Elasticsearch
import pandas as pd
import os

def indexer():
    es = Elasticsearch(
        hosts=["https://host.docker.internal:9200"],
        basic_auth=('elastic', os.getenv("ELASTIC_PASSWORD")),
        verify_certs=False,
        max_retries=30,
        retry_on_timeout=True,
        request_timeout=30,
    )

    if es.ping: 
        print("Connection with Elasticsearch: Success")    
        index = "inversores"

        settings = {
            "settings": {
                "number_of_shards": 1,
                "number_of_replicas": 0
            },
            "mappings": {
                "properties": {
                    "Date": {"type":"date",
                            "format":"dd/MM/yyyy HH:mm"},
                    "Vrms ph-n L1N Mín": { "type": "float"},
                    "Vrms ph-n L1N Méd.": { "type": "float"},
                    "Vrms ph-n L1N Máx": { "type": "float"},
                    "Vrms ph-n L1N Status": { "type": "float"},
                    "Vrms ph-n L2N Mín": { "type": "float"},
                    "Vrms ph-n L2N Méd.": { "type": "float"},
                    "Vrms ph-n L2N Máx": { "type": "float"},
                    "Vrms ph-n L2N Status": { "type": "float"},
                    "Vrms ph-n L3N Mín": { "type": "float"},
                    "Vrms ph-n L3N Méd.": { "type": "float"},
                    "Vrms ph-n L3N Máx": { "type": "float"},
                    "Vrms ph-n L3N Status": { "type": "float"},
                    "Vrms ph-n NG Mín": { "type": "float"},
                    "Vrms ph-n NG Méd.": { "type": "float"},
                    "Vrms ph-n NG Máx": { "type": "float"},
                    "Vrms ph-n NG Status": { "type": "float"},
                    "Vrms ph-ph L12 Mín": { "type": "float"},
                    "Vrms ph-ph L12 Méd.": { "type": "float"},
                    "Vrms ph-ph L12 Máx": { "type": "float"},
                    "Vrms ph-ph L12 Status": { "type": "float"},
                    "Vrms ph-ph L23 Mín": { "type": "float"},
                    "Vrms ph-ph L23 Méd.": { "type": "float"},
                    "Vrms ph-ph L23 Máx": { "type": "float"},
                    "Vrms ph-ph L23 Status": { "type": "float"},
                    "Vrms ph-ph L31 Mín": { "type": "float"},
                    "Vrms ph-ph L31 Méd.": { "type": "float"},
                    "Vrms ph-ph L31 Máx": { "type": "float"},
                    "Vrms ph-ph L31 Status": { "type": "float"},
                    "Corrente L1 Mín": { "type": "float"},
                    "Corrente L1 Méd.": { "type": "float"},
                    "Corrente L1 Máx": { "type": "float"},
                    "Corrente L1 Status": { "type": "float"},
                    "Corrente L2 Mín": { "type": "float"},
                    "Corrente L2 Méd.": { "type": "float"},
                    "Corrente L2 Máx": { "type": "float"},
                    "Corrente L2 Status": { "type": "float"},
                    "Corrente L3 Mín": { "type": "float"},
                    "Corrente L3 Méd.": { "type": "float"},
                    "Corrente L3 Máx": { "type": "float"},
                    "Corrente L3 Status": { "type": "float"},
                    "Corrente N Mín": { "type": "float"},
                    "Corrente N Méd.": { "type": "float"},
                    "Corrente N Máx": { "type": "float"},
                    "Corrente N Status": { "type": "float"},
                    "Freqüência Mín": { "type": "float"},
                    "Freqüência Méd.": { "type": "float"},
                    "Freqüência Máx": { "type": "float"},
                    "Freqüência Status": { "type": "float"},
                    "Assimetria Vn Mín": { "type": "float"},
                    "Assimetria Vn Méd.": { "type": "float"},
                    "Assimetria Vn Máx": { "type": "float"},
                    "Assimetria Vn Status": { "type": "float"},
                    "Assimetria Vz Mín": { "type": "float"},
                    "Assimetria Vz Méd.": { "type": "float"},
                    "Assimetria Vz Máx": { "type": "float"},
                    "Assimetria Vz Status": { "type": "float"},
                    "Assimetria An Mín": { "type": "float"},
                    "Assimetria An Méd.": { "type": "float"},
                    "Assimetria An Máx": { "type": "float"},
                    "Assimetria An Status": { "type": "float"},
                    "Assimetria Az Mín": { "type": "float"},
                    "Assimetria Az Méd.": { "type": "float"},
                    "Assimetria Az Máx": { "type": "float"},
                    "Assimetria Az Status": { "type": "float"},
                    "Potência Ativa L1N Mín": { "type": "float"},
                    "Potência Ativa L1N Méd.": { "type": "float"},
                    "Potência Ativa L1N Máx": { "type": "float"},
                    "Potência Ativa L1N Status": { "type": "float"},
                    "Potência Ativa L2N Mín": { "type": "float"},
                    "Potência Ativa L2N Méd.": { "type": "float"},
                    "Potência Ativa L2N Máx": { "type": "float"},
                    "Potência Ativa L2N Status": { "type": "float"},
                    "Potência Ativa L3N Mín": { "type": "float"},
                    "Potência Ativa L3N Méd.": { "type": "float"},
                    "Potência Ativa L3N Máx": { "type": "float"},
                    "Potência Ativa L3N Status": { "type": "float"},
                    "Potência Ativa Total Mín": { "type": "float"},
                    "Potência Ativa Total Méd.": { "type": "float"},
                    "Potência Ativa Total Máx": { "type": "float"},
                    "Potência Aparente L1N Mín": { "type": "float"},
                    "Potência Aparente L1N Méd.": { "type": "float"},
                    "Potência Aparente L1N Máx": { "type": "float"},
                    "Potência Aparente L1N Status": { "type": "float"},
                    "Potência Aparente L2N Mín": { "type": "float"},
                    "Potência Aparente L2N Méd.": { "type": "float"},
                    "Potência Aparente L2N Máx": { "type": "float"},
                    "Potência Aparente L2N Status": { "type": "float"},
                    "Potência Aparente L3N Mín": { "type": "float"},
                    "Potência Aparente L3N Méd.": { "type": "float"},
                    "Potência Aparente L3N Máx": { "type": "float"},
                    "Potência Aparente L3N Status": { "type": "float"},
                    "Potência Aparente Total Mín": { "type": "float"},
                    "Potência Aparente Total Méd.": { "type": "float"},
                    "Potência Aparente Total Máx": { "type": "float"},
                    "Fator de Potência L1N Mín": { "type": "float"},
                    "Fator de Potência L1N Méd.": { "type": "float"},
                    "Fator de Potência L1N Máx": { "type": "float"},
                    "Fator de Potência L1N Status": { "type": "float"},
                    "Fator de Potência L2N Mín": { "type": "float"},
                    "Fator de Potência L2N Méd.": { "type": "float"},
                    "Fator de Potência L2N Máx": { "type": "float"},
                    "Fator de Potência L2N Status": { "type": "float"},
                    "Fator de Potência L3N Mín": { "type": "float"},
                    "Fator de Potência L3N Méd.": { "type": "float"},
                    "Fator de Potência L3N Máx": { "type": "float"},
                    "Fator de Potência L3N Status": { "type": "float"},
                    "Fator de Potência Total Mín": { "type": "float"},
                    "Fator de Potência Total Méd.": { "type": "float"},
                    "Fator de Potência Total Máx": { "type": "float"},
                    "Energia Ativa L1N Mín": { "type": "float"},
                    "Energia Ativa L1N Méd.": { "type": "float"},
                    "Energia Ativa L1N Máx": { "type": "float"},
                    "Energia Ativa L1N Status": { "type": "float"},
                    "Energia Ativa L2N Mín": { "type": "float"},
                    "Energia Ativa L2N Méd.": { "type": "float"},
                    "Energia Ativa L2N Máx": { "type": "float"},
                    "Energia Ativa L2N Status": { "type": "float"},
                    "Energia Ativa L3N Mín": { "type": "float"},
                    "Energia Ativa L3N Méd.": { "type": "float"},
                    "Energia Ativa L3N Máx": { "type": "float"},
                    "Energia Ativa L3N Status": { "type": "float"},
                    "Energia Ativa Total Mín": { "type": "float"},
                    "Energia Ativa Total Méd.": { "type": "float"},
                    "Energia Ativa Total Máx": { "type": "float"},
                    "THD V L1N Mín": { "type": "float"},
                    "THD V L1N Méd.": { "type": "float"},
                    "THD V L1N Máx": { "type": "float"},
                    "THD V L1N Status": { "type": "float"},
                    "THD V L2N Mín": { "type": "float"},
                    "THD V L2N Méd.": { "type": "float"},
                    "THD V L2N Máx": { "type": "float"},
                    "THD V L2N Status": { "type": "float"},
                    "THD V L3N Mín": { "type": "float"},
                    "THD V L3N Méd.": { "type": "float"},
                    "THD V L3N Máx": { "type": "float"},
                    "THD V L3N Status": { "type": "float"},
                    "THD V NG Mín": { "type": "float"},
                    "THD V NG Méd.": { "type": "float"},
                    "THD V NG Máx": { "type": "float"},
                    "THD V NG Status": { "type": "float"},
                    "THD A L1 Mín": { "type": "float"},
                    "THD A L1 Méd.": { "type": "float"},
                    "THD A L1 Máx": { "type": "float"},
                    "THD A L1 Status": { "type": "float"},
                    "THD A L2 Mín": { "type": "float"},
                    "THD A L2 Méd.": { "type": "float"},
                    "THD A L2 Máx": { "type": "float"},
                    "THD A L2 Status": { "type": "float"},
                    "THD A L3 Mín": { "type": "float"},
                    "THD A L3 Méd.": { "type": "float"},
                    "THD A L3 Máx": { "type": "float"},
                    "THD A L3 Status": { "type": "float"},
                    "THD A N Mín": { "type": "float"},
                    "THD A N Méd.": { "type": "float"},
                    "THD A N Máx": { "type": "float"},
                    "THD A N Status": { "type": "float"}
                }
            }
        }
        
        es.indices.create(index = index, ignore = 400, body = settings)
        
indexer()